version: '3.0'

networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Forecasting_Pipeline
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app_network

