paths:
  artifacts_dir: "artifacts"
  processed_dir : "artifacts/Processed_DFs"
  foresast_dir : "artifacts/Forecasts"
  
  
symbols:
  currencies:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    - DOGEUSDT
    - LINKUSDT



forecast_period: 180

